name: atlas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_theme: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.0"

flutter:
  uses-material-design: true
  assets:
    - assets/appainter_theme.json
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true
  remove_alpha_ios: true